# Generated by Django 6.0 on 2026-01-31 18:52

import insta.validateimage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0004_alter_like_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='post_images/', validators=[insta.validateimage.validate_image]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', validators=[insta.validateimage.validate_image]),
        ),
    ]
